In [4]:
import numpy as np
import scipy.linalg as sp

In [9]:
def centar(T):
    C=sp.null_space(T)
    C = np.where(np.isclose(C, 0) , 0.0 , C)
    return C/C[-1]

In [8]:
T = np.array([[-2,3,0,7], [-3,0,3,-6], [1,0,0,-2]])
print(centar(T))

[[ 2.]
 [-1.]
 [ 4.]
 [ 1.]]


In [48]:
def sredi_znak(Q,R):
    if R[0,0] < 0 :
        R[0,:]*=-1
        Q[:,0]*=-1
    if R[1,1] < 0 :
        R[1,:]*=-1
        Q[:,1]*=-1
    if R[2,2] < 0 :
        R[2,:]*=-1
        Q[:,2]*=-1

In [75]:
def kameraK(T):
    T0=np.asmatrix(T[:,:-1]).I
    T0=np.where(np.isclose(T0, 0) , 0.0 , T0)
    if np.linalg.det(T0) < 0:
        T0*=-1
    Q,R=np.linalg.qr(T0)
    sredi_znak(Q,R)
    K=np.asmatrix(R).I
    K=np.where(np.isclose(K, 0) , 0.0 , K)
    return K/K[2,2]

In [50]:
T = np.array([[-2,3,0,7], [-3,0,3,-6], [1,0,0,-2]])
print(kameraK(T))

[[ 3.  0. -2.]
 [ 0.  3. -3.]
 [ 0.  0.  1.]]


In [72]:
def kameraA(T):
    T0=np.asmatrix(T[:,:-1]).I
    T0=np.where(np.isclose(T0, 0) , 0.0 , T0)
    if np.linalg.det(T0) < 0:
        T0*=-1
    Q,R=np.linalg.qr(T0)
    sredi_znak(Q,R)
    A=np.transpose(Q)
    A=np.where(np.isclose(A, 0) , 0.0 , A)
    return A

In [73]:
T = np.array([[-2,3,0,7], [-3,0,3,-6], [1,0,0,-2]])
print(kameraA(T))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [74]:
T2 = np.array([[-40.76114 , 96.88137  , 5.02608 , 257.87105],
 [-80.7022 , -30.26509 , 64.822  , 433.86004],
 [ -0.02538 , -0.00392 , -0.01387 ,  1.     ]])
print(kameraA(T2))

[[ 0.23389563 -0.95953359 -0.15680601]
 [ 0.4349197   0.24750198 -0.86578729]
 [ 0.86956178  0.13430584  0.47520969]]


In [82]:
def matricaKamere(pts2D, pts3D):
    matrica=[]
    for y,x in zip(pts2D,pts3D):
        prvi=[0,0,0,0,-y[2]*x[0],-y[2]*x[1],-y[2]*x[2],-y[2]*x[3],y[1]*x[0],y[1]*x[1],y[1]*x[2],y[1]*x[3]]
        drugi=[y[2]*x[0],y[2]*x[1],y[2]*x[2],y[2]*x[3],0,0,0,0,-y[0]*x[0],-y[0]*x[1],-y[0]*x[2],-y[0]*x[3]]
        matrica.append(prvi)
        matrica.append(drugi)
    matrica=np.array(matrica)
    U,D,VT=np.linalg.svd(matrica)
    T=VT[-1]
    T=T.reshape(3,4)
    T/=T[2,3]
    T=np.where(np.isclose(T, 0) , 0.0 , T)
    return T

In [83]:
pts2D = np.array([[12, 61, 31], [1, 95, 4], [20, 82, 19], [56, 50, 55], [32, 65, 84], [46, 39, 16], [67, 63, 78]])
pts3D = np.array([[44, 61, 31, 99], [17, 84, 40, 45], [20, 59, 65, 3], [37, 81, 70, 82], [7, 95, 8, 29], [31, 61, 91, 37], [82, 99, 80, 7]])
print(matricaKamere(pts2D,pts3D))

[[-4.95933456e+00 -2.53600395e-01  1.79306654e+00  1.09046525e+00]
 [-6.93111919e+00  4.90342386e-03  3.79892319e+00 -2.18612503e-01]
 [-5.88155295e+00 -3.99314702e-01  2.34600792e+00  1.00000000e+00]]


-----------------Gotove verzije za tester koje samo copy-paste direktno.-------------

1. Zad

Trenutno ne radi zato sto tester na RCUB-u nema verziju scipy u kojoj postoji scipy.linalg.null_space()

In [110]:
import numpy as np
import scipy.linalg as sp
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
 
def centar(T):
    C=sp.null_space(T)
    C = np.where(np.isclose(C, 0) , 0.0 , C)
    C/=C[-1]
    novi=[]
    for x in C:   #Glupa funkcija za formatiranje izlaza za tester
        for y in x:
            novi.append(y)
    return np.array(novi)

Ova verzija radi, samo zato sto direktno implementira scipy.linalg.null_space()

In [111]:
import numpy
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 

def null_space(A, rcond=None):
    u, s, vh = linalg.svd(A, full_matrices=True)
    M, N = u.shape[0], vh.shape[1]
    if rcond is None:
        rcond = numpy.finfo(s.dtype).eps * max(M, N)
    tol = numpy.amax(s) * rcond
    num = numpy.sum(s > tol, dtype=int)
    Q = vh[num:,:].T.conj()
    return Q

def centar(T):
    C=null_space(T)
    C = np.where(np.isclose(C, 0) , 0.0 , C)
    C/=C[-1]
    novi=[]
    for x in C:   #Glupa funkcija za formatiranje izlaza za tester
        for y in x:
            novi.append(y)
    return np.array(novi)

2. Zad

In [ ]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
def sredi_znak(Q,R):
    if R[0,0] < 0 :
        R[0,:]*=-1
        Q[:,0]*=-1
    if R[1,1] < 0 :
        R[1,:]*=-1
        Q[:,1]*=-1
    if R[2,2] < 0 :
        R[2,:]*=-1
        Q[:,2]*=-1
 
def kameraK(T):
    T0=np.asmatrix(T[:,:-1]).I
    T0=np.where(np.isclose(T0, 0) , 0.0 , T0)
    Q,R=np.linalg.qr(T0)
    sredi_znak(Q,R)
    K=np.asmatrix(R).I
    K=np.where(np.isclose(K, 0) , 0.0 , K)
    return K/K[2,2]
 

3. Zad

In [ ]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
def sredi_znak(Q,R):
    if R[0,0] < 0 :
        R[0,:]*=-1
        Q[:,0]*=-1
    if R[1,1] < 0 :
        R[1,:]*=-1
        Q[:,1]*=-1
    if R[2,2] < 0 :
        R[2,:]*=-1
        Q[:,2]*=-1
 
def kameraA(T):
    T0=np.asmatrix(T[:,:-1]).I
    T0=np.where(np.isclose(T0, 0) , 0.0 , T0)
    if np.linalg.det(T0) < 0:
        T0*=-1
    Q,R=np.linalg.qr(T0)
    sredi_znak(Q,R)
    A=np.transpose(Q)
    A=np.where(np.isclose(A, 0) , 0.0 , A)
    return A
 

4. Zad

In [ ]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
 
def matricaKamere(pts2D : np.array, pts3D : np.array):
    matrica=[]
    for y,x in zip(pts2D,pts3D):
        prvi=[0,0,0,0,-y[2]*x[0],-y[2]*x[1],-y[2]*x[2],-y[2]*x[3],y[1]*x[0],y[1]*x[1],y[1]*x[2],y[1]*x[3]]
        drugi=[y[2]*x[0],y[2]*x[1],y[2]*x[2],y[2]*x[3],0,0,0,0,-y[0]*x[0],-y[0]*x[1],-y[0]*x[2],-y[0]*x[3]]
        matrica.append(prvi)
        matrica.append(drugi)
    matrica=np.array(matrica)
    U,D,VT=np.linalg.svd(matrica)
    T=VT[-1]
    T=T.reshape(3,4)
    T/=T[2,3]
    T=np.where(np.isclose(T, 0) , 0.0 , T)
    return T
 